/* tslint:disable */
/* eslint-disable */
/**
 * Simple Test API
 * 簡易テスト用のOpenAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EchoPost200Response,
  EchoPostRequest,
} from '../models/index';
import {
    EchoPost200ResponseFromJSON,
    EchoPost200ResponseToJSON,
    EchoPostRequestFromJSON,
    EchoPostRequestToJSON,
} from '../models/index';

export interface EchoPostOperationRequest {
    echoPostRequest: EchoPostRequest;
}

/**
 * 
 */
export class EchoApi extends runtime.BaseAPI {

    /**
     * メッセージをそのまま返す
     */
    async echoPostRaw(requestParameters: EchoPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EchoPost200Response>> {
        if (requestParameters['echoPostRequest'] == null) {
            throw new runtime.RequiredError(
                'echoPostRequest',
                'Required parameter "echoPostRequest" was null or undefined when calling echoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/echo`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EchoPostRequestToJSON(requestParameters['echoPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EchoPost200ResponseFromJSON(jsonValue));
    }

    /**
     * メッセージをそのまま返す
     */
    async echoPost(requestParameters: EchoPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EchoPost200Response> {
        const response = await this.echoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
