/* tslint:disable */
/* eslint-disable */
/**
 * Simple Test API
 * 簡易テスト用のOpenAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HelloGet200Response,
} from '../models/index';
import {
    HelloGet200ResponseFromJSON,
    HelloGet200ResponseToJSON,
} from '../models/index';

export interface HelloGetRequest {
    name?: string;
}

/**
 * 
 */
export class GreetingApi extends runtime.BaseAPI {

    /**
     * Helloメッセージを返す
     */
    async helloGetRaw(requestParameters: HelloGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HelloGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hello`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HelloGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Helloメッセージを返す
     */
    async helloGet(requestParameters: HelloGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HelloGet200Response> {
        const response = await this.helloGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
