name: 実装依頼
description: 通常の機能追加の対応
title: "[FEATURE] No. "
type: Feature
body:
    - type: markdown
      attributes:
          value: |
              新規の対応用のテンプレートです
    - type: input
      id: parent
      attributes:
        label: マージ先ブランチ
        description: マージ先の対応集約Issue番号を記載してください
        placeholder: '#yyyy年MM月対応'
    - type: input
      id: backlog
      attributes:
        label: backlogリンク
        description: 対応するbacklogリンクを記載してください
    - type: textarea
      id: what-happened
      attributes:
          label: 詳細
          description: 詳細を記入してください
      validations:
          required: false