name: バグ報告
description: 不具合報告用テンプレート
title: "[BUG] #"
body:
    - type: markdown
      attributes:
          value: |
              不具合報告用のテンプレートです
    - type: input
      id: redmine
      attributes:
        label: Redmineリンク
        description: 対応するRedmineリンクを記載してください
      validations:
        required: true
    - type: textarea
      id: what-happened
      attributes:
          label: 詳細
          description: 詳細を記入してください
      validations:
          required: false