/* tslint:disable */
/* eslint-disable */
/**
 * Simple Test API
 * 簡易テスト用のOpenAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EchoPost200Response
 */
export interface EchoPost200Response {
    /**
     * 
     * @type {string}
     * @memberof EchoPost200Response
     */
    text?: string;
}

/**
 * Check if a given object implements the EchoPost200Response interface.
 */
export function instanceOfEchoPost200Response(value: object): value is EchoPost200Response {
    return true;
}

export function EchoPost200ResponseFromJSON(json: any): EchoPost200Response {
    return EchoPost200ResponseFromJSONTyped(json, false);
}

export function EchoPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EchoPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function EchoPost200ResponseToJSON(json: any): EchoPost200Response {
    return EchoPost200ResponseToJSONTyped(json, false);
}

export function EchoPost200ResponseToJSONTyped(value?: EchoPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

