/* tslint:disable */
/* eslint-disable */
/**
 * Simple Test API
 * 簡易テスト用のOpenAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EchoPostRequest
 */
export interface EchoPostRequest {
    /**
     * 
     * @type {string}
     * @memberof EchoPostRequest
     */
    text: string;
}

/**
 * Check if a given object implements the EchoPostRequest interface.
 */
export function instanceOfEchoPostRequest(value: object): value is EchoPostRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function EchoPostRequestFromJSON(json: any): EchoPostRequest {
    return EchoPostRequestFromJSONTyped(json, false);
}

export function EchoPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EchoPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function EchoPostRequestToJSON(json: any): EchoPostRequest {
    return EchoPostRequestToJSONTyped(json, false);
}

export function EchoPostRequestToJSONTyped(value?: EchoPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

