name: Issue作成時 ラベル、マイルストーンを追加

on:
  issues:
    types: [ opened, edited ]

jobs:
  set-issues:
    runs-on: ubuntu-latest

    steps:
      - name: ラベルとマイルストーンを設定
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue?.body) {
              console.log("Issue body is empty or undefined.");
              return;
            }

            // 本文から親Issue番号を取得
            const parentIssueMatch = issue.body.match(/マージ先: #(\d+)/);
            if (!parentIssueMatch) {
              console.log("No issue found in body.");
              return;
            }
            
            const parentIssueNumber = parseInt(parentIssueMatch[1]);

            try {
              // 親issueの情報を取得
              const { data: parentIssue } = await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: parentIssueNumber,
              });

              // フィルタリングするラベルを定義
              const excludedLabels = new Set(["stg", "dev", "fixed", "parent issue", "hotfix", "bug"]);
              const currentIssueLabels = issue.labels.map(label => label.name);
              const labelsToSet = parentIssue.labels
                  .map(label => label.name)
                  .filter(label => !excludedLabels.has(label))
                  .concat(currentIssueLabels);

              // マイルストーンを取得
              const milestoneToSet = parentIssue.milestone?.number || null;

              // issueのラベルとマイルストーンを更新
              await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: labelsToSet,
                  milestone: milestoneToSet,
              });

              console.log(`Updated issue #${issue.number} with labels: ${labelsToSet} and milestone: ${milestoneToSet}`);

            } catch (error) {
              console.error(`Error updating issue #${issue.number}:`, error);
            }