name: Issue作成時テンプレート修正

on:
  issues:
    types: [ opened ]

jobs:
  set-issues:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: ラベルとマイルストーンを設定
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue) {
                throw new Error("Issue payload is not available.");
            }

            console.log(issue);